// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(OnBoardingDbContext))]
    [Migration("20230601173855_AddOnBoardingMockData")]
    partial class AddOnBoardingMockData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.3.23174.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApplicationCore.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<Guid>("EmployeeIdentityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EmployeeStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SSN")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeIdentityId")
                        .IsUnique();

                    b.HasIndex("EmployeeStatusId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St, City 1, Country 1",
                            Email = "aries.mu@GoldSaints.com",
                            EmployeeIdentityId = new Guid("49d65189-9d93-4ba0-9a2e-6cd349a86c6a"),
                            EmployeeStatusId = 1,
                            FirstName = "Aries",
                            LastName = "Mu",
                            SSN = "123-45-6789"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Oak St, City 2, Country 2",
                            Email = "Taurus.Aldebaran@GoldSaints.com",
                            EmployeeIdentityId = new Guid("14467328-f534-4ad3-9eb7-614d33b2814a"),
                            EmployeeStatusId = 1,
                            FirstName = "Taurus",
                            LastName = "Aldebaran",
                            SSN = "234-56-7890"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Elm St, City 3, Country 3",
                            Email = "Gemini.Saga@GoldSaints.com",
                            EmployeeIdentityId = new Guid("cfa82a5b-2e3c-42b9-ade0-4abda5914de6"),
                            EmployeeStatusId = 1,
                            FirstName = "Gemini",
                            LastName = "Saga",
                            SSN = "345-67-8901"
                        },
                        new
                        {
                            Id = 4,
                            Address = "234 Maple St, City 4, Country 4",
                            Email = "Cancer.DeathMask@GoldSaints.com",
                            EmployeeIdentityId = new Guid("0009ced2-db4c-4e05-9459-e375bd2b06ff"),
                            EmployeeStatusId = 1,
                            FirstName = "Cancer",
                            LastName = "DeathMask",
                            SSN = "456-78-9012"
                        },
                        new
                        {
                            Id = 5,
                            Address = "567 Pine St, City 5, Country 5",
                            Email = "Leo.Aiolia@GoldSaints.com",
                            EmployeeIdentityId = new Guid("8c9019dc-ea34-4b05-871a-bcc3ce01633f"),
                            EmployeeStatusId = 1,
                            FirstName = "Leo",
                            LastName = "Aiolia",
                            SSN = "567-89-0123"
                        },
                        new
                        {
                            Id = 6,
                            Address = "890 Cherry St, City 6, Country 6",
                            Email = "Virgo.Shaka@GoldSaints.com",
                            EmployeeIdentityId = new Guid("2035b55f-2d17-4b86-b729-906a3113f4c3"),
                            EmployeeStatusId = 1,
                            FirstName = "Virgo",
                            LastName = "Shaka",
                            SSN = "678-90-1234"
                        },
                        new
                        {
                            Id = 7,
                            Address = "987 Walnut St, City 7, Country 7",
                            Email = "Libra.Dohko@GoldSaints.com",
                            EmployeeIdentityId = new Guid("d0b89c08-2bae-40af-9b50-f906cd7ddbdc"),
                            EmployeeStatusId = 1,
                            FirstName = "Libra",
                            LastName = "Dohko",
                            SSN = "789-01-2345"
                        },
                        new
                        {
                            Id = 8,
                            Address = "876 Cedar St, City 8, Country 8",
                            Email = "Scorpio.Milo@GoldSaints.com",
                            EmployeeIdentityId = new Guid("81bc38d5-1bb1-4c61-bd9f-b074fcf50e74"),
                            EmployeeStatusId = 1,
                            FirstName = "Scorpio",
                            LastName = "Milo",
                            SSN = "890-12-3456"
                        },
                        new
                        {
                            Id = 9,
                            Address = "765 Birch St, City 9, Country 9",
                            Email = "Sagittarius.Aiolos@GoldSaints.com",
                            EmployeeIdentityId = new Guid("e6ba17d4-5712-418d-8e49-fe41ae74b043"),
                            EmployeeStatusId = 1,
                            FirstName = "Sagittarius",
                            LastName = "Aiolos",
                            SSN = "901-23-4567"
                        },
                        new
                        {
                            Id = 10,
                            Address = "654 Willow St, City 10, Country 10",
                            Email = "Capricorn.Shura@GoldSaints.com",
                            EmployeeIdentityId = new Guid("4200a89b-2aad-4b94-bb65-d131fe5b4000"),
                            EmployeeStatusId = 1,
                            FirstName = "Capricorn",
                            LastName = "Shura",
                            SSN = "012-34-5678"
                        },
                        new
                        {
                            Id = 11,
                            Address = "543 Ash St, City 11, Country 11",
                            Email = "Aquarius.Camus@GoldSaints.com",
                            EmployeeIdentityId = new Guid("1e0ca156-a75f-48aa-8262-82fc1461461c"),
                            EmployeeStatusId = 1,
                            FirstName = "Aquarius",
                            LastName = "Camus",
                            SSN = "987-65-4321"
                        },
                        new
                        {
                            Id = 12,
                            Address = "432 Cypress St, City 12, Country 12",
                            Email = "Pisces.Aphrodite@GoldSaints.com",
                            EmployeeIdentityId = new Guid("2f793398-4c0c-4469-8002-a5905acd0136"),
                            EmployeeStatusId = 1,
                            FirstName = "Pisces",
                            LastName = "Aphrodite",
                            SSN = "876-54-3210"
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.EmployeeStatusLookUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmployeeStatusCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("EmployeeStatusDescription")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.HasKey("Id");

                    b.ToTable("EmployeeStatusLookUps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeStatusCode = "Active",
                            EmployeeStatusDescription = "The employee is currently employed"
                        },
                        new
                        {
                            Id = 2,
                            EmployeeStatusCode = "On Leave",
                            EmployeeStatusDescription = "The employee is on an approved leave of absence"
                        },
                        new
                        {
                            Id = 3,
                            EmployeeStatusCode = "Terminated",
                            EmployeeStatusDescription = "The employee's employment has been terminated"
                        },
                        new
                        {
                            Id = 4,
                            EmployeeStatusCode = "Onboarding",
                            EmployeeStatusDescription = "The employee is in the process of being onboarded"
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.Employee", b =>
                {
                    b.HasOne("ApplicationCore.Entities.EmployeeStatusLookUp", "EmployeeStatusLookUp")
                        .WithMany()
                        .HasForeignKey("EmployeeStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeStatusLookUp");
                });
#pragma warning restore 612, 618
        }
    }
}
